# Create secrets with
# kubectl create secret generic backboard-secrets \
#   --from-literal=DB_URL=url \
#   --from-literal=BACKBOARD_GITHUB_TOKEN=xyzzy
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backboard
  name: backboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backboard
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backboard
    spec:
      containers:
        - image: "gcr.io/cockroach-dev-inf/cockroachdb/backboard:master"
          imagePullPolicy: Always
          name: backboard
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  key: DB_URL
                  name: backboard-secrets
            - name: BACKBOARD_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: BACKBOARD_GITHUB_TOKEN
                  name: backboard-secrets
          command: [
            "backboard",
            "--bind", "0.0.0.0:80",
            "--conn", "$(DB_URL)",
            "--branch", "release-23.1",
          ]
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            initialDelaySeconds: 600
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 10
            httpGet:
              path: /healthz?ready=1
              port: http
          resources:
            requests:
              # Fairly minimal steady-state requirements.
              cpu: "100m"
              memory: "512Mi"
            limits:
              # Needs more CPU and memory when bootstrapping.
              cpu: "2"
              memory: "1Gi"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: secrets
          secret:
            secretName: backboard-secrets
            defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backboard
  name: backboard
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: backboard
  type: NodePort
